version: '2'
services:
  proxy:
    image: haproxy:1
    container_name: proxy
    restart: always
    ports:
#      - 80:80
#      - 445:445
#      - 2049:2049
      - 14500:14500 # required to access wireshark, change first port if necessary
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:Z
  wireshark:
    image: "ffeldhaus/wireshark:0.5"
    container_name: wireshark
    restart: always
    privileged: true
    network_mode: "service:proxy"
    environment:
      - XPRA_PW=wireshark # password to access wireshark
    volumes:
      - ./caps:/home/wireshark
  juice:
    image: bkimminich/juice-shop
    ports:
      - 3000:3000
  secutils:
    image: michelborck/secutils
    container_name: secutils
    ports:
      - "514:514/tcp"
      - "514:514/udp"
    volumes:
      - ./data:/data
